language: node_js
node_js:
  - "5.3.0"
services:
  - mongodb
before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start

script: make test && make coverage

script: make coveralls || true
